# `Library Numpy`

`What is Numpy ??`
- NumPy is a Python library used for working with a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays. It also has functions for working in domain of linear algebra, fourier transform, and matrices.

- NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely. NumPy stands for Numerical Python.

`Why Use NumPy ??`
- In Python we have lists that serve the purpose of arrays, but they are slow to process. NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.

- The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy. Arrays are very frequently used in data science, where speed and resources are very important.

`How to install ??`
- pip install numpy
- conda install numpy

In [ ]:
import numpy as np

In [ ]:
print(np.__version__)

1.22.4


## `Get Started With Array in Numpy`

### 1. Array In Numpy

In [ ]:
a = np.array([1,2,3,4,5,6])
b = np.array([[1,2,3,4], [5,6,7,8]])
c = np.array([[[2,1,9,1],[4,5,2,9]],[[8,5,0,3],[4,7,1,5]]])

### 2. Print The Array

In [ ]:
print('1 Dimension :',a,'\n')
print('2 Dimension :\n',b,'\n')
print('3 Dimension :\n',c)

1 Dimension : [1 2 3 4 5 6] 

2 Dimension :
 [[1 2 3 4]
 [5 6 7 8]] 

3 Dimension :
 [[[2 1 9 1]
  [4 5 2 9]]

 [[8 5 0 3]
  [4 7 1 5]]]


### 3. Checking The Type

In [ ]:
print(type(a))
print(type(b))
print(type(c))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


### 4. Checking The Dimension in Arrays

In [ ]:
d = np.array(24)
print(a.ndim, b.ndim, c.ndim, d.ndim)

1 2 3 0


### 5. Numpy Array Indexing

In [ ]:
print(a)

[1 2 3 4 5 6]


In [ ]:
print(a[3])

4


In [ ]:
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
print(b[1,3])

8


In [ ]:
print(c)

[[[2 1 9 1]
  [4 5 2 9]]

 [[8 5 0 3]
  [4 7 1 5]]]


In [ ]:
print(c[0,1,2])

2


### 6. Data types in Numpy

`Numpy has some extra data types, and refer to data types with one character, like i for integers, u for unsigned integers etc.`
- i => integer
- b => Boolean
- u => unsigned integer
- f => float
- c => complex float
- S => string
- m => timedelta

In [ ]:
x = np.array([1,2,3,4,5,6,7,8,9])
print(x.dtype)
y = np.array(['Yudi', 'Budi', 'Candra'])
print(y.dtype)

int64
<U6


In [ ]:
t = np.array([5.7,4.2,8.4])
# print(t.dtype)
t = t.astype('i')
print(t.dtype)

int32


### 7. Shape and Reshape

`The shape of an array is the number of
elements in each dimension.`
- NumPy arrays have an attribute called
shape that returns a tuple with each
index having the number of
corresponding elements.
- Reshaping means changing the shape
of an array.

In [ ]:
c

array([[[2, 1, 9, 1],
        [4, 5, 2, 9]],

       [[8, 5, 0, 3],
        [4, 7, 1, 5]]])

In [ ]:
print(a.shape)
print('(Columns,)', '\n')
print(b.shape)
print('(Rows, Columns)', '\n')
print(c.shape)
print('(Dimension, Rows, Columns)')

(6,)
(Columns,) 

(2, 4)
(Rows, Columns) 

(2, 2, 4)
(Dimension, Rows, Columns)


In [ ]:
print(a.reshape(3,2))

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
print(a.reshape(-1))

[1 2 3 4 5 6]


### 8. Iterating In Array

In [ ]:
a

array([1, 2, 3, 4, 5, 6])

In [ ]:
for ANGKA2 in a :
    print(ANGKA2+2)

3
4
5
6
7
8


In [ ]:
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
for ANGKA2 in b :
#     print(ANGKA2)
    for angkadidalam in ANGKA2 :
        print(angkadidalam)

1
2
3
4
5
6
7
8


In [ ]:
c

array([[[2, 1, 9, 1],
        [4, 5, 2, 9]],

       [[8, 5, 0, 3],
        [4, 7, 1, 5]]])

In [ ]:
for x in c:
#     print(x)
    for y in x:
        print(y)

[2 1 9 1]
[4 5 2 9]
[8 5 0 3]
[4 7 1 5]


### 9. Iterating Array Using nditer

The function nditer() is a helping
function that can be used from very
basic to very advanced iterations. It
solves some basic issues which we
face in iteration which is when we iterate array with very high dimensionality.

In [ ]:
c

array([[[2, 1, 9, 1],
        [4, 5, 2, 9]],

       [[8, 5, 0, 3],
        [4, 7, 1, 5]]])

In [ ]:
for x in np.nditer(c):
    print(x)

2
1
9
1
4
5
2
9
8
5
0
3
4
7
1
5


### 10. Joining Arrays

`Concatenation` refers to putting the contents of `two or more` arrays in a single array. In Python NumPy, we can `join arrays` by axes (vertical or horizontal), whereas in SQL we join tables based on keys.

    ~ Join array must have some dimension

In [ ]:
arr1 = np.array([7, 4, 10])
arr2 = np.array([6, 5, 3])
arr3 = np.array([[1,2,3],[4,5,6]])
arr4 = np.array([[6, 5, 3],[2,7,8]])
arr5 = np.array([[1,2],[5,6],[9,10],[13,17],[19,21],[24,27]])

In [ ]:
# Example 1: Use concatenate() to join two arrays
Join1 = np.concatenate((arr2, arr1))
Join1

array([ 6,  5,  3,  7,  4, 10])

In [ ]:
print(arr3,'\n', arr4)

[[1 2 3]
 [4 5 6]] 
 [[6 5 3]
 [2 7 8]]


In [ ]:
# Example 2: Use concatenate() with axis (for dimension more than 1, we use axis=1)
Join2 = np.concatenate((arr3, arr4), axis=1)
print(Join2)

[[1 2 3 6 5 3]
 [4 5 6 2 7 8]]


In [ ]:
# Example 3: Use np.stack() function to Join Arrays
# Joining 2 array and increase the dimension into next dimension. If u join array with both 2 dimension and it will be 3 dimension, etc

Join3 = np.stack((arr3, arr4), axis=1)
print(Join3)

[[[1 2 3]
  [6 5 3]]

 [[4 5 6]
  [2 7 8]]]


In [ ]:
arr1

array([ 7,  4, 10])

In [ ]:
arr2

array([6, 5, 3])

In [ ]:
# Example 4: Use np.hstack() function
Join4 = np.hstack((arr1, arr2))
print(Join4)

[ 7  4 10  6  5  3]


In [ ]:
# Example 5: Use np.vstack() function 
Join5 = np.vstack((arr1, arr2))
print(Join5)

[[ 7  4 10]
 [ 6  5  3]]


In [ ]:
print(arr3,'\n')
print(arr4)

[[1 2 3]
 [4 5 6]] 

[[6 5 3]
 [2 7 8]]


In [ ]:
# Example 6: Use np.dstack() function to Stacking Along Height (depth)
con = np.dstack((arr3, arr4))
print(con)

[[[1 6]
  [2 5]
  [3 3]]

 [[4 2]
  [5 7]
  [6 8]]]


### 11. Splitting Arrays

In [ ]:
arr1

array([ 7,  4, 10])

In [ ]:
print(np.array_split(arr1,3))
arr1

[array([7]), array([4]), array([10])]


array([ 7,  4, 10])

In [ ]:
arr5

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 17],
       [19, 21],
       [24, 27]])

In [ ]:
print(np.array_split(arr5,3))
arr5

[array([[1, 2],
       [5, 6]]), array([[ 9, 10],
       [13, 17]]), array([[19, 21],
       [24, 27]])]


array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 17],
       [19, 21],
       [24, 27]])

### 12. Searching Arrays

`Where()` is used for `searching` a `certain value` and return the `indexes` that get a match

In [ ]:
a = np.array([1,2,3,4,5,4,7,4,9,10])
print(np.where(a==4))

(array([3, 5, 7]),)


In [ ]:
# Algoritma Searching python

In [ ]:
# We use searchsorted() which performs a linear search. So it return index from the first match value

a = np.array([1,1,2,2,4,5,5,7,8,8])
print(np.searchsorted(a, 8))

8


### 13.Sorting Arrays

`np.random.randint` is used for resulting a random number with `max` and `min value` of number. And it can make `not just 1 dimension array`.

In [ ]:
a = np.random.randint(5, size=(2, 4))
print(a,'\n')
print(np.sort(a))

[[4 3 2 4]
 [1 0 3 4]] 

[[2 3 4 4]
 [0 1 3 4]]


### 14. Filtering Arrays

In [ ]:
a = np.array([1,2,5])
Index = [True, False, True]
print('This is list :', a[Index])

print('This is not a list :', a[0], a[1], a[2])

This is list : [1 5]
This is not a list : 1 2 5


### Get product in array

To `find` the `product` of the `elements in an array`, use the `prod()` function.

A `product` in `math` is defined as the `result of two or more numbers when multiplied together`.

In [ ]:
a= np.array([1,2,3,4,5])
print(np.prod(a))

120


In [ ]:
a= np.array([1,2,3,4,5])
print(np.cumprod(a))

[  1   2   6  24 120]


### Rounding Decimals

There are `primarily five ways` of
`rounding off decimals` in `NumPy`:

- `Truncation` => To `remove` the `decimals` and return the float number `closest to Zero`

- `Fix` => Same with Truncation
- `Rounding` = Round the decimals
- `Floor` => rounds off decimal to nearest upper integer.
- `Ceil` => rounds off decimal to nearest loweer integer.

In [ ]:
deci = np.array([5.768, 4.285, 8.470, 10.585, 85.456, 10.5])

In [ ]:
#rounds off decimal to nearest upper integer.

np.ceil(deci)

array([ 6.,  5.,  9., 11., 86., 11.])

In [ ]:
# rounds off decimal to nearest lower integer.

np.floor(deci)

array([ 5.,  4.,  8., 10., 85., 10.])

In [ ]:
# Remove the decimals and return the float number closest to zero

np.trunc(deci)
np.fix(deci)

array([ 5.,  4.,  8., 10., 85., 10.])

In [ ]:
deci2 = np.array([50.45, 4.585567, 10.50])
np.around(deci2)

array([50.,  5., 10.])

## `Numpy Random`

`Random number` does `NOT mean a different number` every time. `Random means` something that `can not be predicted logically`

_`Random is not a unique number :)`_

### 1. Random.randint()

`Generate a random integer` from `x` to `n` values.

In [ ]:
for i in range(5):
    print(np.random.randint(0,100), '', end = "")

87 47 6 9 29 

In [ ]:
for i in range(5):
    print(np.random.randint(0,100,3), '', end = "")

[38 80 89] [11 40 36] [11 68 57] [ 0 12 66] [56 15  4] 

In [ ]:
for i in range(5):
    print(np.random.randint(0,100,(3,2)))

[[82 49]
 [66 99]
 [99 26]]
[[ 9 95]
 [67 13]
 [77 63]]
[[80 53]
 [ 2 84]
 [44 55]]
[[35 11]
 [ 2 99]
 [29 28]]
[[44 42]
 [72 76]
 [99 62]]


### 2. Random.rand()

Returns a `random float` between `0` and `1`.

In [ ]:
for i in range(5):
    print(np.random.rand(), '', end = "")

0.37446321504131774 0.9292726685750562 0.14789554640411706 0.7243056112483851 0.637977696361349 

### 3. Random.choice()

Allows you `to generate` a `random` value `based on` an `array of values`.

In [ ]:
Nama = ['Rendika', 'Wisnu', 'Dara']

for i in range(1):
    print(np.random.choice(Nama), '', end = "")

Dara 

### 4. Random.choice() with probabilities in each value

In [ ]:
r = np.random.choice([3,5,7,9], p=[0.1, 0.3, 0.6, 0.0], size =(15))

print(r)

[7 5 5 7 7 7 5 7 7 5 5 7 5 7 7]


### 5. Random.randn()

Generate random between negative and positive number.

In [ ]:
np.random.randn(2, 4)

array([[-0.66494046, -0.36201385,  0.46183258, -0.70109889],
       [ 0.73440323, -1.00064759,  0.59140112,  0.94237609]])

### 6. Random.shuffle()

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
np.random.shuffle(arr)
print(arr)

[3 2 4 5 1]


# `Matrix in Numpy`

### 1. Matrix Identity

In [ ]:
g = np.identity(5)

print(g)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


### 2. Matrix Ones

In [ ]:
k = np.ones((4,3), dtype=np.int64)
k = np.ones((4,3), dtype=np.float64)

print(k)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


### 3. Generating Arrays

In [ ]:
n = np.arange(0, 100)
print(n)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [ ]:
n = np.linspace(2, 10, 10, endpoint=True)
print(n)

[ 2.          2.88888889  3.77777778  4.66666667  5.55555556  6.44444444
  7.33333333  8.22222222  9.11111111 10.        ]


### 4. Matrix Operations

In [ ]:
# Addition of Two Matrices

A = np.array([[2, 4], [5, -6]])
B = np.array([[9, -3], [3, 6]])
C = A + B      # element wise addition
print(A,'+\n', B,'\n')
print(C)

[[ 2  4]
 [ 5 -6]] +
 [[ 9 -3]
 [ 3  6]] 

[[11  1]
 [ 8  0]]


In [ ]:
# subtraction of Two Matrices

A = np.array([[2, 4], [5, -6]])
B = np.array([[9, -3], [3, 6]])
C = A - B      # element wise addition
print(A,'-\n', B,'\n')
print(C)

[[ 2  4]
 [ 5 -6]] -
 [[ 9 -3]
 [ 3  6]] 

[[ -7   7]
 [  2 -12]]


In [ ]:
# Multiplication of Two Matrices

A = np.array([[3, 6, 7], [5, -3, 0]])
B = np.array([[1, 1], [2, 1], [3, -3]])
C = A.dot(B)
print(C)

[[ 36 -12]
 [ -1   2]]


### 5. Transpose of a Matrix

In [ ]:
A = np.array([[1, 1], [2, 1], [3, -3]])
print(A,'\n')

[[ 1  1]
 [ 2  1]
 [ 3 -3]] 



In [ ]:
print(A.transpose())

[[ 1  2  3]
 [ 1  1 -3]]
